-- Website branding, banner/theme settings, and influencer vouchers.
-- Run once against the app database (no migration tool in this repo — see backend/migrations/README.md).

CREATE TABLE IF NOT EXISTS site_settings (
    id integer PRIMARY KEY DEFAULT 1,
    brand_name character varying(100) NOT NULL DEFAULT 'Tandoor',
    logo_url text,
    banner_images jsonb NOT NULL DEFAULT '[]'::jsonb,
    primary_color character varying(20) NOT NULL DEFAULT '#2563EB',
    secondary_color character varying(20) NOT NULL DEFAULT '#DBEAFE',
    background_color character varying(20) NOT NULL DEFAULT '#F3F4F6',
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT site_settings_singleton CHECK (id = 1)
);

INSERT INTO site_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS vouchers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(50) NOT NULL UNIQUE,
    label character varying(150),
    discount_type character varying(10) NOT NULL DEFAULT 'percent',
    discount_value numeric(10,2) NOT NULL,
    max_discount_cap numeric(10,2),
    min_order_amount numeric(10,2) NOT NULL DEFAULT 0,
    max_uses integer,
    used_count integer NOT NULL DEFAULT 0,
    expires_at timestamp without time zone,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT vouchers_discount_type_check CHECK (discount_type IN ('percent', 'fixed'))
);

-- Track which voucher (if any) was applied to an order, and the discount actually charged.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS voucher_code character varying(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount numeric(10,2) NOT NULL DEFAULT 0;

-- The public website already reads branch.phone/branch.city (call button, city filter)
-- but the table never had these columns — add them, nullable, so those features work.
ALTER TABLE branches ADD COLUMN IF NOT EXISTS phone character varying(20);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS city character varying(100);

-- Lets the admin explicitly curate the "Popular Items" section on the website
-- instead of it being auto-derived from whichever products happen to have a photo.
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_popular boolean NOT NULL DEFAULT false;

-- Categories aren't a first-class table (just distinct products.category strings),
-- so a category's picture is tracked separately, keyed by branch + name.
CREATE TABLE IF NOT EXISTS category_images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    name character varying(100) NOT NULL,
    image_url text,
    image_public_id text,
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE (branch_id, name)
);

-- Product customization: groups of add-ons (e.g. "Choose Patty" single-select,
-- "Add Cheese"/"Fries"/"Beverages" multi-select), each with priced options.
-- Separate from product_variants (which POS/cashier/orders already depend on)
-- so this is purely additive for the public website's product configurator.
CREATE TABLE IF NOT EXISTS addon_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    title character varying(100) NOT NULL,
    selection_type character varying(10) NOT NULL DEFAULT 'single',
    required boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT addon_groups_selection_type_check CHECK (selection_type IN ('single', 'multiple'))
);

CREATE TABLE IF NOT EXISTS addon_options (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL REFERENCES addon_groups(id) ON DELETE CASCADE,
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL DEFAULT 0,
    is_available boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0
);

-- Record exactly which add-ons were chosen on a placed order (for receipts/history).
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS selected_addons jsonb NOT NULL DEFAULT '[]'::jsonb;
