-- Per-product discount pricing (actual price + discounted price shown with strikethrough),
-- and a proper table-management + running-tab system for dine-in orders.

ALTER TABLE products ADD COLUMN IF NOT EXISTS discounted_price numeric(10,2);

-- Restaurant's own tables (admin-managed, matching the physical floor plan).
CREATE TABLE IF NOT EXISTS restaurant_tables (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id integer NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    name character varying(50) NOT NULL,
    seats integer,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE (branch_id, name)
);

-- A dine-in order now tracks which table it belongs to, and whether the tab is
-- still open (cashier can keep adding items) or has been finalized/billed.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS restaurant_table_id integer REFERENCES restaurant_tables(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tab_status character varying(10) NOT NULL DEFAULT 'closed';
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_tab_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_tab_status_check CHECK (tab_status IN ('open', 'closed'));

-- Website checkout already collects an email but it was never stored/used — needed for order confirmation emails.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_email character varying(150);

-- Lets the admin control the display order of categories (website + POS), not just their pictures.
ALTER TABLE category_images ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;
